### ISSUE TITLE
Implement a command line interface to Open Weathermap API in your language of choice

### ISSUE THREAD

**Issue by managedkaos** [managedkaos/openweathermap-cli#1]
Implement a command line interface to the Open Weather Map API using the language of your choice _or_ improve on the solutions already in place.

1.  **Note that you will need to create your own API key and place it in the file named `apikey.txt` at the top level.**  All *.txt files should be ignored via .gitignore file.

1. Read the [project requirements here.](https://github.com/managedkaos/openweathermap-cli/blob/master/README.md)

2. If you create a new CLI, create a new folder under the top level with the name of the language you used, starting with an Uppercase letter.  

3. Inside that folder, implement your CLI in a file named `weather` (no extension).  If the implementation must be compiled, use the language extension and add a README.md with steps for compiling the code to an executable named `weather`.

4. Update `test.sh` in the Test directory to call your script or program.

Happy hacking!

-ManagedKaos

**Comment by nkilm** [comment]
I would like to work on this using `python3`. Please assign this issue to me!

**Comment by managedkaos** [comment]
@nkilm feel free to fork and start a PR! This issue will remain open for anyone that wants to pick it up.  Cheers! 😄

**Comment by nkilm** [comment]
@managedkaos  Okay😄
